<?php
/**
 * SearchRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\WebSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Web Setup Api
 *
 * API to setup a program on a website
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Softonic\WebSetupApiSdk;

/**
 * SearchRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SearchRequest
 * @package     Softonic\WebSetupApiSdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchRequest"
     */
    public function testSearchRequest()
    {
    }

    /**
     * Test attribute "id_program"
     */
    public function testPropertyIdProgram()
    {
    }

    /**
     * Test attribute "id_platform"
     */
    public function testPropertyIdPlatform()
    {
    }

    /**
     * Test attribute "id_language"
     */
    public function testPropertyIdLanguage()
    {
    }
}
