<?php
/**
 * ProgramsPlatformsLanguagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\WebSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Web Setup Api
 *
 * API to setup a program on a website
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\WebSetupApiSdk;

use Softonic\WebSetupApiSdk\Configuration;
use Softonic\WebSetupApiSdk\ApiException;
use Softonic\WebSetupApiSdk\ObjectSerializer;

/**
 * ProgramsPlatformsLanguagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\WebSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsPlatformsLanguagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProgramPlatformLanguage
     *
     * Creates a program configuration for a specific platform and language.
     *
     */
    public function testCreateProgramPlatformLanguage()
    {
    }

    /**
     * Test case for deleteProgramPlatformLanguage
     *
     * Deletes a program configuration for a specific platform and language.
     *
     */
    public function testDeleteProgramPlatformLanguage()
    {
    }

    /**
     * Test case for findProgramPlatformLanguage
     *
     * Finds a program configuration for a specific platform for all languages.
     *
     */
    public function testFindProgramPlatformLanguage()
    {
    }

    /**
     * Test case for readProgramPlatformLanguage
     *
     * Reads a program configuration for a specific platform and language.
     *
     */
    public function testReadProgramPlatformLanguage()
    {
    }

    /**
     * Test case for replaceProgramPlatformLanguage
     *
     * Replaces a program configuration for a specific platform and language.
     *
     */
    public function testReplaceProgramPlatformLanguage()
    {
    }

    /**
     * Test case for updateProgramPlatformLanguage
     *
     * Updates a program configuration for a specific platform and language.
     *
     */
    public function testUpdateProgramPlatformLanguage()
    {
    }
}
