<?php
/**
 * SearchApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\WebSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Web Setup Api
 *
 * API to setup a program on a website
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\WebSetupApiSdk;

use Softonic\WebSetupApiSdk\Configuration;
use Softonic\WebSetupApiSdk\ApiException;
use Softonic\WebSetupApiSdk\ObjectSerializer;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\WebSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for search
     *
     * Search a list of filters and returns the result.
     *
     */
    public function testSearch()
    {
    }
}
